### ISSUE TITLE
TypeError when running kmos view

### ISSUE THREAD

**Issue by stabilowl** [mhoffman/kmos#66]
When trying to visualize model with kmos view, a TypeError related to View._ _init_ _() is returned. Seems to occur in the view.py file. 

### Expected behavior
Display the model

### Actual behavior
Traceback (most recent call last):
  File "/home/williaml/.local/bin/kmos", line 21, in <module>
    main()
  File "/home/williaml/.local/lib/python2.7/site-packages/kmos/cli.py", line 426, in main
    view.main(steps_per_frame=options.steps_per_frame)
  File "/home/williaml/.local/lib/python2.7/site-packages/kmos/view.py", line 452, in main
    viewer = KMC_Viewer(model, steps_per_frame=steps_per_frame)
  File "/home/williaml/.local/lib/python2.7/site-packages/kmos/view.py", line 398, in _ _init_ _
    self.vbox, self.window)
  File "/home/williaml/.local/lib/python2.7/site-packages/kmos/view.py", line 174, in _ _init_ _
    View._ _init_ _(self, self.vbox, rotations)
TypeError: _ _init_ _() takes exactly 2 arguments (3 given)

[//]: # (Besides the text description, include any screenshot(s) that help us visualize the issue you're facing)

### Steps to reproduce the issue
1. Have both .so and kmc_settings.py in the directory
2. type kmc view on terminal at the folder
3.

### System information

- result of `kmos version`, operating system, version, python version, possibly link to model file
kmos version 0.3.9
ubuntu 16.04 LTS
Python 2.7.12

```

```
[//]: # (If you experienced crashes, segfaults please also include a stacktrace below.)

**Comment by stabilowl** [comment]
Thanks! That looked like it fixed the issue.  Thanks for the quick reply
